In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.15.0


In [6]:
hello=tf.constant('Hello')

In [7]:
world=tf.constant('World')

In [8]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [9]:
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result =sess.run(hello+world)

we also use 

sess=tf.Session()

result=sess.run(hello+world) 

but here manually sess.close() required

In [11]:
print(result)

b'HelloWorld'


In [12]:
a=tf.constant(10)

In [13]:
b=tf.constant(20)

In [14]:
type(a)

tensorflow.python.framework.ops.Tensor

In [15]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [16]:
with tf.Session() as sess:
    result =sess.run(a+b)

In [17]:
result

30

In [18]:
const=tf.constant(10)

In [19]:
fill_mat=tf.fill((4,4),10)

In [20]:
myzeros=tf.zeros((4,4))

In [21]:
myones=tf.ones((4,4))

In [26]:
myrandn=tf.random_normal((4,4),mean=0,stddev=1.0)

In [30]:
myrandu=tf.random_uniform((4,4),minval=0,maxval=1)

In [31]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [32]:
my_ops=[const,fill_mat,myzeros,myones,myrandn,myrandu]

In [33]:
sess=tf.InteractiveSession()

In [34]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.18703036 -0.66263837 -0.00369525  0.2674227 ]
 [-0.7761093  -0.02159034  0.6682355  -0.36561513]
 [-1.712116    0.8088523   2.1435013  -0.12018101]
 [-0.04840421  1.9690601  -0.6802076  -2.7629402 ]]


[[0.14702082 0.8686657  0.31805444 0.17603719]
 [0.24282765 0.06250596 0.85315156 0.8771038 ]
 [0.90936565 0.7894939  0.84771585 0.28728485]
 [0.74207544 0.14955807 0.6858038  0.95695925]]




In [35]:
a=tf.constant([[1,2],[3,4]])

In [36]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [37]:
b=tf.constant([[10],[100]])

In [38]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [39]:
result=tf.matmul(a,b)

In [40]:
sess.run(result)

array([[210],
       [430]])

In [41]:
result.eval()

array([[210],
       [430]])